trigger: 
 branches:
   include:
     - main
 paths:
   include:
     - Terraform-Kubecluster/*
variables:
  tag: $(Build.BuildId)
pool:
  name: ATC

steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'atc-azurecontainerreg-connection-svc'
        repository: 'proj-webapp'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: $(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'atc-azurecontainerreg-connection-svc'
        repository: 'proj-webapp'
        command: 'push'
        tags: $(tag)
    
        
    

    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'atc-kubercluster-connection-svc'
        namespace: 'default'
        manifests: 'manifests/*.yml'
        containers: 'atcprojwebappcontainerreg.azurecr.io/proj-webapp:$(tag)'
